---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/projects":
    post:
      summary: Creates Project
      tags:
      - Projects
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Project is created
          content:
            application/json:
              example:
                data:
                  id: 97cecb94-c5c6-4182-bd90-1a9c926ef8ba
                  type: project
                  attributes:
                    title: cumque
        '401':
          description: Unauthorized
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                errors:
                  title:
                  - Title is required.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - project
              properties:
                project:
                  type: object
                  required:
                  - title
                  - project_id
                  properties:
                    title:
                      type: string
                      example: modi
                    user_id:
                      type: string
                      example: f220de21-24e3-4000-bc24-ac9a09ca3819
  "/api/v1/session":
    post:
      summary: Creates Session
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: Session is created
          content:
            application/json:
              example:
                data:
                  id: fce0f47a-0445-4ab2-8c14-b6508b49a378
                  type: user_account
                  attributes:
                    username: ricardahedlund valentin_sjberg
                meta:
                  csrf: O9PqOg7WXasErDUtuIbt3bLYIzPMl8F/Er+TK1/DBUeNl4PCL96zE3fg2+snq+gyl07gVYnXJ0fkzXkUwkwJCQ==
                  access: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDUyMjEwNzYsInVzZXJfaWQiOiJmY2UwZjQ3YS0wNDQ1LTRhYjItOGMxNC1iNjUwOGI0OWEzNzgiLCJuYW1lc3BhY2UiOiJ1c2VyLWFjY291bnQtc2Vzc2lvbi1mY2UwZjQ3YS0wNDQ1LTRhYjItOGMxNC1iNjUwOGI0OWEzNzgiLCJ1aWQiOiJmZTYxYzY4OS04MzUzLTQ2NjktOTE5MS1iN2U5Zjk4OWE2ZjIifQ.emHDrWofzOlpMqw3W7KbLfiDM-9n-BgCp6K-xx54Nmc
                  access_expires_at: '2022-02-18T23:51:16.000+02:00'
                  refresh: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDUyNjA2NzYsInVzZXJfaWQiOiJmY2UwZjQ3YS0wNDQ1LTRhYjItOGMxNC1iNjUwOGI0OWEzNzgiLCJuYW1lc3BhY2UiOiJ1c2VyLWFjY291bnQtc2Vzc2lvbi1mY2UwZjQ3YS0wNDQ1LTRhYjItOGMxNC1iNjUwOGI0OWEzNzgiLCJ1aWQiOiI1YWI0MWU2My0wMTFkLTQxNTMtOThkYi00MzA5ZGYzMWNiYTkifQ.BinysM6g1UoLh2CauyJPZTip4dqpCE0gwf6pIqezOJs
                  refresh_expires_at: '2022-02-19T10:51:16.000+02:00'
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                errors:
                  username:
                  - The field is required.
                  password:
                  - The field is required.
        '401':
          description: Invalid credentials
          content:
            application/json:
              example:
                errors:
                  base:
                  - Invalid username or password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - username
              - password
              properties:
                username:
                  type: string
                  example: kam
                password:
                  type: string
                  example: I4dsuxI0
    delete:
      summary: Destroys Session
      tags:
      - Sessions
      parameters:
      - name: X-Refresh-Token
        in: header
        description: Refresh Token
        schema:
          type: string
      responses:
        '204':
          description: Session is destroyed
        '403':
          description: Not authorized
  "/api/v1/user":
    post:
      summary: Creates User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User is created
        '422':
          description: Invalid params
          content:
            application/json:
              example:
                errors:
                  username:
                  - The field is required.
                  password:
                  - The field is required.
                  password_confirmation:
                  - The field is required.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - user
              properties:
                user:
                  type: object
                  required:
                  - username
                  - password
                  - password_confirmation
                  properties:
                    username:
                      type: string
                      example: gaylordabrahamsson
                    password:
                      type: string
                      example: Abc43Dea
                    password_confirmation:
                      type: string
                      example: Abc43Dea
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
