
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.dig(:db, :host) || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || Rails.application.credentials.dig(:db, :user) %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: to_do_list_api_development
staging:
  <<: *default
  database: to_do_list_api_staging
production:
  <<: *default
  database: to_do_list_api_production
test:
  <<: *default
  database: to_do_list_api_test