
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.dig(:db, :host) || 'localhost' %>
  username: <%= Rails.application.credentials.dig(:db, :user) || ENV['DB_USER'] %>
  password: <%= Rails.application.credentials.dig(:db, :password) || ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: to_do_list_api_development
staging:
  <<: *default
  database: to_do_list_api_staging
production:
  <<: *default
  database: to_do_list_api_production
test:
  <<: *default
  database: to_do_list_api_test
